export const MISC_SELECTEDPLAYLIST_SET = 'MISC_SELECTEDPLAYLIST_SET';
export const MISC_SELECTEDPLAYLIST_CLEAR = 'MISC_SELECTEDPLAYLIST_CLEAR';
export const MISC_SONGNAVSELECTION_SET = 'MISC_SONGNAVSELECTION_SET';
export const PLAYLIST = 'SONGNAVSELECTIONTYPE/PLAYLIST';
export const SEARCH = 'SONGNAVSELECTIONTYPE/SEARCH';
export const QUEUE = 'SONGNAVSELECTIONTYPE/QUEUE';
