export const PLAYLISTS_REQUEST = 'PLAYLISTS_REQUEST';
export const PLAYLISTS_REQUEST_FAILURE = 'PLAYLISTS_REQUEST_FAILURE';
export const PLAYLISTS_REQUEST_SUCCESS = 'PLAYLISTS_REQUEST_SUCCESS';

export const PLAYLISTS_ADD_SONG = 'PLAYLISTS_ADD_SONG';
export const PLAYLISTS_ADD_SONG_ID = 'PLAYLISTS_ADD_SONG_ID';

export const PLAYLISTS_CREATE = 'PLAYLISTS_CREATE';
