export const SEARCH_MEDIA_REQUEST = 'SEARCH_MEDIA_REQUEST';
export const SEARCH_MEDIA_REQUEST_SUCCESS = 'SEARCH_MEDIA_REQUEST_SUCCESS';
export const SEARCH_YOUTUBE_REQUEST_FAILURE = 'SEARCH_YOUTUBE_REQUEST_FAILURE';

export const SEARCH_SONG_CLEAR_RESULTS = 'SEARCH_SONG_CLEAR_RESULTS';
