export const SEARCH_YOUTUBE_REQUEST = 'SEARCH_YOUTUBE_REQUEST';
export const SEARCH_YOUTUBE_REQUEST_FAILURE = 'SEARCH_YOUTUBE_REQUEST_FAILURE';
export const SEARCH_YOUTUBE_REQUEST_SUCCESS = 'SEARCH_YOUTUBE_REQUEST_SUCCESS';
