export const PLAYING_START = 'PLAYING_START';
export const PLAYING_END = 'PLAYING_END';
export const PLAYING_SET_TIME = 'PLAYING_SET_TIME';
export const PLAYING_SET_SONG = 'PLAYING_SET_SONG';
export const PLAYING_SET_DURATION = 'PLAYING_SET_DURATION';
export const PLAYING_SET_VOLUME = 'PLAYING_SET_VOLUME';
export const PLAYING_START_SEEK = 'PLAYING_START_SEEK';
export const PLAYING_STOP_SEEK = 'PLAYING_STOP_SEEK';
