export const PLAYING_START = 'PLAYING_START';
export const PLAYING_END = 'PLAYING_END';
export const PLAYING_SET_TIME = 'PLAYING_SET_TIME';
export const PLAYING_SET_SONG = 'PLAYING_SET_SONG';
export const PLAYING_SET_DURATION = 'PLAYING_SET_DURATION';
